[tools]
bun = "latest"
fzf = "latest"
gh = "latest"
graphite = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
python = "latest"
starship = "latest"
terraform = "latest"
yarn = "latest"
yq = "latest"
